In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name' : ['John', 'Anna', 'Peter', 'Linda'],
    'Age' : [28,32,59,22],
    'City': ['New York', 'London','Paris', 'Berlin'],
    'Salary': [64000,43000,23000,66000]
}
df = pd.DataFrame(data)

In [3]:
df

    Name  Age      City  Salary
0   John   28  New York   64000
1   Anna   32    London   43000
2  Peter   59     Paris   23000
3  Linda   22    Berlin   66000

In [23]:
data_list = [
    ['John', 'Anna', 'Peter', 'Linda'],
     [28,32,59,22],
    ['New York', 'London','Paris', 'Berlin'],
    [64000,43000,23000,66000]
]

dl = pd.DataFrame(data_list)
# indexing
col = ['Name','Age','City','Random']
dl = pd.DataFrame(data_list,columns=col)
dl

       Name     Age   City  Random
0      John    Anna  Peter   Linda
1        28      32     59      22
2  New York  London  Paris  Berlin
3     64000   43000  23000   66000

In [24]:
# selecting Rows/Cols

In [25]:
dl[['Name','Age']]

       Name     Age
0      John    Anna
1        28      32
2  New York  London
3     64000   43000

In [26]:
dl.loc[[0,1]]

   Name   Age   City Random
0  John  Anna  Peter  Linda
1    28    32     59     22

In [27]:
# Add column in the table

In [28]:
dl['Random'] = ['aa','asda','ada','ad']

In [29]:
dl

       Name     Age   City Random
0      John    Anna  Peter     aa
1        28      32     59   asda
2  New York  London  Paris    ada
3     64000   43000  23000     ad

In [30]:
# removing a row/column

In [31]:
dl.drop('Random',axis = 1)

       Name     Age   City
0      John    Anna  Peter
1        28      32     59
2  New York  London  Paris
3     64000   43000  23000

In [32]:
dl

       Name     Age   City Random
0      John    Anna  Peter     aa
1        28      32     59   asda
2  New York  London  Paris    ada
3     64000   43000  23000     ad

In [33]:
dl.drop('Random',axis=1,inplace=True)

In [34]:
dl

       Name     Age   City
0      John    Anna  Peter
1        28      32     59
2  New York  London  Paris
3     64000   43000  23000

In [35]:
dl.drop(0,axis=0)

       Name     Age   City
1        28      32     59
2  New York  London  Paris
3     64000   43000  23000

In [36]:
dl

       Name     Age   City
0      John    Anna  Peter
1        28      32     59
2  New York  London  Paris
3     64000   43000  23000

In [ ]:
# Selecting a subset of rows/column

In [37]:
df

    Name  Age      City  Salary
0   John   28  New York   64000
1   Anna   32    London   43000
2  Peter   59     Paris   23000
3  Linda   22    Berlin   66000

In [38]:
df.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   59
3  Linda   22

In [ ]:
# Conditional Selection

In [39]:
df

    Name  Age      City  Salary
0   John   28  New York   64000
1   Anna   32    London   43000
2  Peter   59     Paris   23000
3  Linda   22    Berlin   66000

In [40]:
df[df['Age'] < 30]

    Name  Age      City  Salary
0   John   28  New York   64000
3  Linda   22    Berlin   66000

In [41]:
df[(df['Age'] < 30) & (df['City'] == 'Berlin')]

    Name  Age    City  Salary
3  Linda   22  Berlin   66000