In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Finding Missing Data

In [5]:
data = {
    'A' : [1,2,np.nan,4,5],
    'B' : [1,2,3,4,5],
    'C' : [1,2,3,np.nan,np.nan],
    'D' : [1, np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [6]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [11]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [12]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
# Removing Missing Data

df

In [13]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [16]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Filling the Missing Values

In [18]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [19]:
v = {'A' : 20, 'B': 30,'C':10,'D': 60}
df.fillna(value=v)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  60.0
2  20.0  3   3.0  60.0
3   4.0  4  10.0  60.0
4   5.0  5  10.0   5.0

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

#

#

#

#